title: ベターモノ<span style="font-size:smaller;">(Better Things)</span>
logo: /assets/img/logo.png
description: <b>ヘタもの</b>の下手のところを理解して、<b>ベターモノ</b>を作る。
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
