title: <span style="font-size:smaller;">ベターモノ<br><span style="font-size:smaller;">(Better Things)</span></span>
logo: /assets/img/logo.png
description: <strong>ヘタもの</strong>の下手のところを理解して、<strong>ベターモノ</strong>にする。
link0: 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
